version: '3.8'

services:
  web:
    image: 15cm/thanatosns
    restart: unless-stopped
    entrypoint: ["/init"]
    env_file:
      - ./docker-compose.env
    depends_on:
      - redis
      - db
    volumes:
      - data-export:/data/thanatosns/export
    ports:
      - 3000:3000

  celery:
    image: 15cm/thanatosns
    restart: unless-stopped
    command: pdm run celery -A thanatosns worker -l INFO
    env_file:
      - ./docker-compose.env
    depends_on:
      - redis
      - db
    volumes:
      - data-export:/data/thanatosns/export

  flower:
    image: 15cm/thanatosns
    restart: unless-stopped
    command: pdm run celery --broker=redis://redis:6379/1 flower
    env_file:
      - ./docker-compose.env
    depends_on:
      - redis
      - task-worker
    ports:
      - 5555:5555

  sh:
    image: 15cm/thanatosns
    profiles: ["admin"]
    env_file:
      - ./docker-compose.env
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.0.11
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  db:
    image: postgres:15.3
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  data-export:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /tmp/thanatosns
