version: '3.8'

services:
  web:
    image: thanatosns
    restart: unless-stopped
    entrypoint: ["/init"]
    env_file:
      - ./docker-compose.env
    depends_on:
      - redis
      - db
    ports:
      - 3000:3000

  redis:
    image: redis:7.0.11
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  db:
    image: postgres:15.3
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    environment:
      - POSTGRES_PASSWORD=postgres

  sh:
    image: thanatosns
    profiles: ["admin"]
    env_file:
      - ./docker-compose.env
    depends_on:
      - redis
      - db
