
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Sinkerine", email = "git@15cm.net"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
]
