# Generated by Django 4.2.2 on 2023-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
