# Generated by Django 4.2.2 on 2023-07-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="authors",
            field=models.ManyToManyField(related_name="posts", to="posts.author"),
        ),
    ]
