# Generated by Django 4.2.2 on 2023-07-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_published_at_author_post_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="index",
            field=models.PositiveIntegerField(),
        ),
    ]
