# Generated by Django 4.2.3 on 2023-07-13 05:56

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_metadata"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="author",
            name="posts_autho_other_n_605dcf_gin",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="other_names",
            new_name="names",
        ),
        migrations.RemoveField(
            model_name="author",
            name="name",
        ),
        migrations.AddField(
            model_name="author",
            name="handle",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="author",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["names"], name="posts_autho_names_e44ad6_gin"
            ),
        ),
    ]
