# Generated by Django 4.2.2 on 2023-07-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_post_published_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="media",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.UniqueConstraint(
                fields=("url", "index", "post"), name="unique_media_per_post"
            ),
        ),
    ]
