# Generated by Django 4.2.2 on 2023-07-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_media_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="url",
            field=models.CharField(max_length=255),
        ),
    ]
