# Generated by Django 4.2.2 on 2023-07-07 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_media_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="content_type",
        ),
    ]
