# Generated by Django 4.2.2 on 2023-07-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_remove_media_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="authors",
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts.author",
            ),
        ),
    ]
