# Generated by Django 4.2.2 on 2023-07-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_remove_post_authors_post_author"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="media",
            name="unique_media_per_post",
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.UniqueConstraint(
                fields=("index", "post"), name="unique_media_per_post"
            ),
        ),
    ]
