#!/command/with-contenv sh
cd /opt/thanatosns/thanatosns
pdm run gunicorn thanatosns.asgi:application --workers ${THANATOSNS_GUNICORN_WORKERS_NUM:-4} --worker-class uvicorn.workers.UvicornWorker --bind 127.0.0.1:8000