# Generated by Django 4.2.2 on 2023-07-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostExportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exporter_id", models.CharField(max_length=255)),
                ("is_exported", models.BooleanField()),
                ("exported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_statuses",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Post export statuses",
            },
        ),
        migrations.AddConstraint(
            model_name="postexportstatus",
            constraint=models.UniqueConstraint(
                fields=("exporter_id", "post"), name="unique_exporter_per_post"
            ),
        ),
    ]
