# Generated by Django 4.2.2 on 2023-07-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("export", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postexportstatus",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="postexportstatus",
            constraint=models.UniqueConstraint(
                fields=("exporter_id", "post"), name="unique_exporter_per_post"
            ),
        ),
    ]
