# Generated by Django 4.2.2 on 2023-07-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("export", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postexportstatus",
            name="export_path",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
