# Generated by Django 4.2.2 on 2023-07-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_remove_post_authors_post_author"),
        ("export", "0002_alter_postexportstatus_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postexportstatus",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="export_statuses",
                to="posts.post",
            ),
        ),
    ]
