# Generated by Django 4.2.2 on 2023-07-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0002_alter_media_post_alter_post_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostExportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exporter_id", models.CharField(max_length=255)),
                ("is_exported", models.BooleanField()),
                ("exported_at", models.DateTimeField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_status",
                        to="posts.post",
                    ),
                ),
            ],
        ),
    ]
