# Generated by Django 4.2.2 on 2023-07-05 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_media_post_alter_post_authors"),
        ("exporters", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postexportstatus",
            options={"verbose_name_plural": "Post export statuses"},
        ),
        migrations.AlterUniqueTogether(
            name="postexportstatus",
            unique_together={("exporter_id", "post")},
        ),
    ]
