# Generated by Django 4.2.2 on 2023-07-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exporters", "0002_alter_postexportstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postexportstatus",
            name="exported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
